import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import CarTile from "../components/CarTile";
import Header from "../components/Header";

export default function Home({ cars }) {
  return (
    <div className="bg-gray-200 min-h-screen w-full">
      <Head>
        <title>Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-4xl mx-auto h-full p-8">
        <div>
          <div className="mb-4 flex items-center justify-between">
            <h2 className="text-3xl text-blue-600 font-semibold ">
              Tracking cars list
            </h2>
            <Link href="/new_tracker">
              <a className="text-white px-8 py-2 bg-blue-600 rounded-md">
                New Tracker
              </a>
            </Link>
          </div>
          {cars.length}
          <div className="space-y-2">
            {cars.map((car) => (
              //console.log(car)
              <CarTile car={car} key={car.id} />
            ))}
          </div>
        </div>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const response = await fetch("http://localhost:5001/trackers");
  const cars = await response.json();
  console.log(cars);

  return {
    props: {
      cars,
    },
  };
}
