import Head from "next/head";
import Image from "next/image";
import CarTile from "../components/CarTile";

const cars = [
  {
    id: 1,
    name: "Actros 2822 54 ",
    company: "Palos",
    trafic: "Butembo-Nairobi",
    status: "actif",
    imgUrl: "/camion1.jpg",
  },
  {
    id: 2,
    name: "Mercedes Benz -- 2 tank ",
    company: "Palos",
    trafic: "Goma-Nairobi",
    status: "actif",
    imgUrl: "/camion2.jpg",
  },
  {
    id: 3,
    name: "Actros 224 ",
    company: "Palos",
    trafic: "Butembo-Nairobi",
    status: "actif",
    imgUrl: "/transitgood.jpg",
  },
  {
    id: 4,
    name: "Actros 225 ",
    company: "Palos",
    trafic: "Butembo-Nairobi",
    status: "actif",
    imgUrl: "/transitgood.jpg",
  },
];

export default function Home() {
  return (
    <div className="bg-gray-200 min-h-screen w-full">
      <Head>
        <title>Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className=" bg-blue-600 w-full sticky top-0">
        <div className="max-w-4xl mx-auto flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <img src="/logoo.png" className="w-16 h-16  object-center" alt="" />
            <h2 className="text-2xl font-bold text-blue-50">Tracking cars</h2>
          </div>
          <div className=" flex items-center space-x-4 ">
            <a
              href=""
              className="text-white hover:text-orange-600 hover:font-semibold hover:underline hover:underline-offset-4"
            >
              Acceuil
            </a>
            <a
              href=""
              className="text-white hover:text-orange-600 hover:font-semibold hover:underline hover:underline-offset-4"
            >
              Clients
            </a>
            <a
              href=""
              className="text-white hover:text-orange-600 hover:font-semibold hover:underline hover:underline-offset-4"
            >
              Services
            </a>
          </div>
        </div>
      </header>

      <main className="max-w-4xl mx-auto h-full p-8">
        <div>
          <h2 className="text-3xl text-blue-600 font-semibold mb-4">
            Liste des camions en tracking
          </h2>
          <div className="space-y-2">
            {cars.map((car) => (
              <CarTile car={car} key={car.id} />
            ))}
          </div>
        </div>
      </main>
    </div>
  );
}
